spring:
  application:
    name: job-analysis
  profiles:
    active: prod
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        service-name: job-analysis
        instance-id: job-analysis-${machine.ip}-${server.port}
        scheme: http
        enabled: true

ribbon:
  ServerListRefreshInterval: 3000

management:
  endpoints:
    web:
      exposure:
        include: health,configprops,env,beans,conditions,loggers,metrics,mappings,prometheus,scheduledtasks
      base-path: /actuator
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    configprops:
      enabled: true
    env:
      enabled: true
    beans:
      enabled: true
    conditions:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    mappings:
      enabled: true
    prometheus:
      enabled: true
    scheduledtasks:
      enabled: true
  metrics:
    tags:
      application: ${spring.cloud.consul.discovery.service-name}
server:
  port: 19807
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

