apiVersion: v2
name: "bk-job"
description: A Helm chart for Blueking Job
type: application
version: 0.1.0
appVersion: "3.4.0"

dependencies:
- name: common
  version: 1.4.1
  repository: https://charts.bitnami.com/bitnami
- name: nginx-ingress-controller
  version: 7.4.8
  repository: https://charts.bitnami.com/bitnami
  condition: nginx-ingress-controller.enabled
- name: mongodb
  version: 10.10.2
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled
