spring:
  datasource:
    job-file-gateway:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: ${job.file-gateway.db.url}
      username: ${job.file-gateway.db.username}
      password: ${job.file-gateway.db.password}
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      poolName: "job-file-gateway"
      validationTimeout: 5000
  redis:
    mode: ${job.file-gateway.redis.mode:sentinel}
    host: ${job.file-gateway.redis.host:}
    port: ${job.file-gateway.redis.port:6379}
    sentinel:
      password: ${job.file-gateway.redis.sentinel.password:}
      master: ${job.file-gateway.redis.sentinel.master:}
      nodes: ${job.file-gateway.redis.sentinel.nodes:}
    password: ${job.file-gateway.redis.password:}
    database: ${job.file-gateway.redis.database}
    lettuce:
      pool:
        min-idle: ${job.file-gateway.redis.lettuce.pool.min-idle:5}
        max-idle: ${job.file-gateway.redis.lettuce.pool.max-idle:10}
        max-active: ${job.file-gateway.redis.lettuce.pool.max-idle:8}
        max-wait: ${job.file-gateway.redis.lettuce.pool.max-wait:1ms}
      shutdown-timeout: ${job.file-gateway.redis.lettuce.shutdown-timeout:100ms}
  servlet:
    multipart:
      max-file-size: ${job.file-gateway.upload.filesize.max:5GB}
      max-request-size: ${job.file-gateway.upload.filesize.max:5GB}

job:
  security:
    service:
      private-key-base64: ${job.security.private-key-base64}
      public-key-base64: ${job.security.public-key-base64}
