apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-gateway-%s" (include "common.names.fullname" .) "tls-cert" }}
  labels:
    {{- include "common.labels.standard" . | indent 4 }}
    { { - if .Values.commonLabels } }
    { { - include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 } }
    { { - end } }
  namespace: {{ .Release.Namespace }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | indent 4 }}
    {{- end }}
type: Opaque
data:
  job_server.keystore: {{ .Files.Get "cert/job_server.p12" | b64enc }}
  job_server.truststore: {{ .Files.Get "cert/job_server.truststore" | b64enc }}
  keystore.password: {{ .Values.gatewayConfig.server.ssl.keystore.password | b64enc | quote }}
  truststore.password: {{ .Values.gatewayConfig.server.ssl.truststore.password | b64enc | quote }}

